# TOML specifications : https://toml.io/en/

# Doc : https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

[versions]
junitV = "4.13.2"
kotlinV = "1.5.30"
asmV = "9.2"
groovy-allV = "3.0.9"
agpV = "7.0.2"
aspectjV = "1.9.7"


[libraries]
junit = { module = "junit:junit", version.ref = "junitV" }

agp = { module = "com.android.tools.build:gradle", version.ref = "agpV" }
ktGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinV" }
ktStdJdk = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinV" }

# asm : https://asm.ow2.io/
asm = { module = "org.ow2.asm:asm", version.ref = "asmV" }

# aspectJ : https://github.com/eclipse/org.aspectj
aspectj-lib = { module = "org.aspectj:aspectjlib", version = "1.6.2" }

aspectj-jrt = { module = "org.aspectj:aspectjrt", version.ref = "aspectjV" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectjV" }
aspectj-tools = { module = "org.aspectj:aspectjtools", version.ref = "aspectjV" }
aspectj-matcher = { module = "org.aspectj:aspectjmatcher", version.ref = "aspectjV" }

groovyAll = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy-allV" }



[bundles]
base =['ktStdJdk','groovyAll']
aspectj =['aspectj-lib','aspectj-jrt','aspectj-weaver','aspectj-tools','aspectj-matcher']


